version: '3.9'
services:

  shell:
    build:
      context: ./shell
      dockerfile: Dockerfile.dev
    volumes:
      - ./shell:/app
      - /app/node_modules
    ports:
      - "3000:3000"

  mfe-visa:
    build:
      context: ./mfe-visa
      dockerfile: Dockerfile.dev
    volumes:
      - ./mfe-visa:/app
      - /app/node_modules
    ports:
      - "3001:3000"

  mfe-tour:
    build:
      context: ./mfe-tour
      dockerfile: Dockerfile.dev
    volumes:
      - ./mfe-tour:/app
      - /app/node_modules
    ports:
      - "3002:3000"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - shell
      - mfe-tour
      - mfe-visa
