version: '3'
services:
  nuxt-shell:
    build:
      context: ./nuxt-shell
    ports:
      - "3000:3000"
    networks:
      - app-network

  microfrontend-1:
    build:
      context: ./microfrontend-1
    ports:
      - "3001:3001"
    networks:
      - app-network

  microfrontend-2:
    build:
      context: ./microfrontend-2
    ports:
      - "3002:3002"
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nuxt-shell
      - microfrontend-1
      - microfrontend-2
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
